replicaCount: 2

image:
  registry: docker.io
  repository: viafluvial/via-fluvial-keycloak-themes
  tag: "26.0.0"
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  publicHost: keycloak.exemplo.vfa.jus.br
  adminHost: keycloak-admin.exemplo.vfa.jus.br
  tls:
    enabled: true

resources:
  limits:
    cpu: "2"
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 75

nodeSelector: {}
tolerations: []
affinity: {}

keycloak:
  startCommand:
    - start
    - --import-realm

  hostname: keycloak.exemplo.vfa.jus.br
  hostnameAdmin: keycloak-admin.exemplo.vfa.jus.br
  hostnameStrict: true
  proxyHeaders: xforwarded

  db:
    vendor: postgres
    host: postgresql.vfa.svc.cluster.local
    port: 5432
    database: keycloak
    username: keycloak
    poolInitialSize: 5
    poolMaxSize: 40

  cache:
    type: ispn
    stack: kubernetes

  observability:
    healthEnabled: true
    metricsEnabled: true
    logLevel: INFO

  bootstrapAdmin:
    username: admin

  theme:
    loginTheme: vfa-platform
    accountTheme: keycloak.v3
    adminTheme: keycloak.v2
    emailTheme: keycloak

secrets:
  bootstrapAdminPassword: ""
  dbPassword: ""
  googleClientId: ""
  googleClientSecret: ""

extraEnv: []

pdb:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: false
  ingressFromNamespaces: []
