apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vfa.fullname" . }}-secrets
  labels:
    {{- include "vfa.labels" . | nindent 4 }}
type: Opaque
stringData:
  KC_BOOTSTRAP_ADMIN_PASSWORD: {{ required "secrets.bootstrapAdminPassword is required" .Values.secrets.bootstrapAdminPassword | quote }}
  KC_DB_PASSWORD: {{ required "secrets.dbPassword is required" .Values.secrets.dbPassword | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
